services:
  postgres:
    image: postgres
    container_name: payment_gateway
    restart: always
    environment:
      POSTGRES_USER: kamal
      POSTGRES_PASSWORD: kdeen265
      POSTGRES_DB: 2099_gateway
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/postgresql/
volumes:
  db:
    driver: local
  