"""add receipt table

Revision ID: 3c80308165fb
Revises:
Create Date: 2026-07-04 11:37:07.242856

"""

from typing import Sequence, Union

import sqlalchemy as sa
from psycopg import Transaction

from alembic import op
from src.enums.transaction_states import TransactionStates

# revision identifiers, used by Alembic.
revision: str = "3c80308165fb"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment_receipt",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column(
            "current_state",
            sa.Enum(
                "PENDING",
                "AUTHORIZED",
                "VOIDED",
                "CAPTURED",
                "REFUNDED",
                name="transactionstates",
            ),
            nullable=False,
            default=TransactionStates.PENDING,
        ),
        sa.Column("authorization_id", sa.String(length=100), nullable=True),
        sa.Column("capture_id", sa.String(length=100), nullable=True),
        sa.Column("void_id", sa.String(length=100), nullable=True),
        sa.Column("refund_id", sa.String(length=100), nullable=True),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("captured_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("voided_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("refunded_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("state_transitioned_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_customer_id", "payment_receipt", ["customer_id"], unique=False)
    op.create_index(
        "idx_order_id_transaction_state",
        "payment_receipt",
        ["order_id", "current_state"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payment_receipt_customer_id"),
        "payment_receipt",
        ["customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payment_receipt_order_id"),
        "payment_receipt",
        ["order_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payment_receipt_order_id"), table_name="payment_receipt")
    op.drop_index(op.f("ix_payment_receipt_customer_id"), table_name="payment_receipt")
    op.drop_index("idx_order_id_transaction_state", table_name="payment_receipt")
    op.drop_index("idx_customer_id", table_name="payment_receipt")
    op.drop_table("payment_receipt")
    # ### end Alembic commands ###
