"""add idempotency_id foreign key to idempotency_audit

Revision ID: 699078e92173
Revises: bb9ea0b39767
Create Date: 2026-07-04 12:26:57.387949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '699078e92173'
down_revision: Union[str, Sequence[str], None] = 'bb9ea0b39767'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idempotency_audit', sa.Column('idempotency_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'idempotency_audit', 'idempotency_keys', ['idempotency_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'idempotency_audit', type_='foreignkey')
    op.drop_column('idempotency_audit', 'idempotency_id')
    # ### end Alembic commands ###
