"""add state history table

Revision ID: 6bc2b35f1cb0
Revises: dcc1d772cbd8
Create Date: 2026-07-04 11:43:27.842495

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6bc2b35f1cb0"
down_revision: Union[str, Sequence[str], None] = "dcc1d772cbd8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

### By me
## Edited the enum columns to postgresql.ENUM to prevent alembic from creating enum type againt


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "state_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "previous_state",
            postgresql.ENUM(
                "PENDING",
                "AUTHORIZED",
                "VOIDED",
                "CAPTURED",
                "REFUNDED",
                name="transactionstates",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "transitioned_state",
            postgresql.ENUM(
                "PENDING",
                "AUTHORIZED",
                "VOIDED",
                "CAPTURED",
                "REFUNDED",
                name="transactionstates",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("transitioned_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("receipt_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["receipt_id"], ["payment_receipt.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("state_history")
    # ### end Alembic commands ###
