"""add all tables

Revision ID: ce6063fb3999
Revises: 
Create Date: 2026-07-13 19:51:13.054494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce6063fb3999'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_receipt',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('current_state', sa.Enum('PENDING', 'AUTHORIZING', 'AUTHORIZED', 'VOIDING', 'VOIDED', 'CAPTURING', 'CAPTURED', 'REFUNDING', 'REFUNDED', 'FAILED', name='transactionstates'), nullable=False),
    sa.Column('authorization_id', sa.String(length=100), nullable=True),
    sa.Column('capture_id', sa.String(length=100), nullable=True),
    sa.Column('void_id', sa.String(length=100), nullable=True),
    sa.Column('refund_id', sa.String(length=100), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('captured_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('voided_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('refunded_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('state_transitioned_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_customer_id', 'payment_receipt', ['customer_id'], unique=False)
    op.create_index('idx_order_id_transaction_state', 'payment_receipt', ['order_id', 'current_state'], unique=False)
    op.create_index(op.f('ix_payment_receipt_customer_id'), 'payment_receipt', ['customer_id'], unique=False)
    op.create_index(op.f('ix_payment_receipt_order_id'), 'payment_receipt', ['order_id'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('last_run_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('locked_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('request_method', sa.String(length=10), nullable=False),
    sa.Column('request_params', sa.JSON(), nullable=False),
    sa.Column('request_path', sa.String(length=100), nullable=False),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.JSON(), nullable=True),
    sa.Column('recovery_point', sa.String(length=50), nullable=False),
    sa.Column('receipt_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['receipt_id'], ['payment_receipt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receipt_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('receipt_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['receipt_id'], ['payment_receipt.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('state_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('previous_state', sa.Enum('PENDING', 'AUTHORIZING', 'AUTHORIZED', 'VOIDING', 'VOIDED', 'CAPTURING', 'CAPTURED', 'REFUNDING', 'REFUNDED', 'FAILED', name='transactionstates'), nullable=False),
    sa.Column('transitioned_state', sa.Enum('PENDING', 'AUTHORIZING', 'AUTHORIZED', 'VOIDING', 'VOIDED', 'CAPTURING', 'CAPTURED', 'REFUNDING', 'REFUNDED', 'FAILED', name='transactionstates'), nullable=False),
    sa.Column('transitioned_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('receipt_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['receipt_id'], ['payment_receipt.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('idempotency_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('idempotency_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idempotency_id'], ['idempotency_keys.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('idempotency_audit')
    op.drop_table('state_history')
    op.drop_table('receipt_audit')
    op.drop_table('idempotency_keys')
    op.drop_index(op.f('ix_payment_receipt_order_id'), table_name='payment_receipt')
    op.drop_index(op.f('ix_payment_receipt_customer_id'), table_name='payment_receipt')
    op.drop_index('idx_order_id_transaction_state', table_name='payment_receipt')
    op.drop_index('idx_customer_id', table_name='payment_receipt')
    op.drop_table('payment_receipt')
    # ### end Alembic commands ###
