"""add idempotency keys table

Revision ID: dcc1d772cbd8
Revises: 3c80308165fb
Create Date: 2026-07-04 11:39:05.917473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcc1d772cbd8'
down_revision: Union[str, Sequence[str], None] = '3c80308165fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('last_run_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('locked_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('request_method', sa.String(length=10), nullable=False),
    sa.Column('request_params', sa.JSON(), nullable=False),
    sa.Column('request_path', sa.String(length=100), nullable=False),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.JSON(), nullable=True),
    sa.Column('recovery_point', sa.String(length=50), nullable=False),
    sa.Column('receipt_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['receipt_id'], ['payment_receipt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('idempotency_keys')
    # ### end Alembic commands ###
